/* FILE: AVIS/VERSION 1/BOOT/init.boot
   ROLE: VERSION_BOOTSTRAP
   VERSION: 1
*/

BEGIN BOOT VERSION_1
    LOAD_CONFIG("AVIS/VERSION 1/CONFIG/version.cfg");
    LOAD_SECURITY("AVIS/VERSION 1/SECURITY/policy.sec");
    LOAD_ENGINE("AVIS/VERSION 1/ENGINE/cyborg.engine");
    LOAD_INTERPRETER("AVIS/VERSION 1/INTERPRETER/loader.fvs");
    LOAD_MATRIX("AVIS/VERSION 1/ARTIFACTS/matrix.instance.art");
    LOAD_EXTENSIONS("AVIS/VERSION 1/EXTENSIONS/loader.ext");
    SIGNAL EVENT_INIT;
END BOOT
