name: FIRE-SITE

on:
  push:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run sitemap script
        run: |
          chmod +x SITEMAP.SH
          ./SITEMAP.SH

      - name: Commit and push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "actions@github.com"

          git add -A

          if ! git diff --staged --quiet; then
            git commit -m "Update sitemap"
            git push
          else
            echo "No changes."
          fi
